# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Machine Learning Open Course
author: Open Academy
copyright: 2022-2022
logo: logo.png
only_build_toc_files: false

html:
  favicon: "favicon.ico" 

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  exclude_patterns:
    - 'assignments/**/*'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/open-academy/machine-learning/  # Online location of your book
  path_to_book: open-machine-learning-jupyter-book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
        <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a> Text content of this work is licensed under the <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub.
  thebe: true

sphinx:
  config:
    html_favicon: favicon.ico
  extra_extensions:
    - sphinxcontrib.mermaid
    - sphinxcontrib.wavedrom
    - sphinxcontrib.plantuml
    - sphinxcontrib.tikz
    - sphinxcontrib.blockdiag
    - sphinxcontrib.drawio
    - sphinxcontrib.quizdown