# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Ocademy Open Machine Learning Book
author: Ocademy
copyright: 2022-2023
logo: logo-long.png
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  exclude_patterns:
    - 'assignments/*'
    - 'assignments/**/*'
    - 'deep-learning/*'
    - 'deep-learning/*/*'
    - 'slides/*'
    - 'slides/**/*'
    - 'ml-advanced/ensemble-learning/random-forest.ipynb'
    - 'ml-advanced/clustering/introduction-to-clustering.ipynb'
    - 'ml-advanced/clustering/k-means-clustering.ipynb'
    - 'ml-advanced/unsupervised-learning-pca-and-clustering.ipynb'
    - 'ml-advanced/unsupervised-learning.ipynb'
    - 'data-science/data-science-in-the-cloud/the-azure-ml-sdk-way.ipynb'
    - 'llm/basic/transformer.ipynb'
    
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - colon_fence
    - deflist
    - linkify
    - replacements
    - smartquotes
    - substitution

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ocademy-ai/machine-learning/  # Online location of your book
  path_to_book: open-machine-learning-jupyter-book  # Optional path to your book, relative to the repository root
  branch: release  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "favicon.ico"
  home_page_in_navbar: false
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
        <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a> Text content of this work is licensed under the <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
  comments:
      utterances:
        repo: "ocademy-ai/machine-learning-utterances"
        issue-term: "pathname"
        theme: "github-light"
  announcement: "Learn AI together, for free! At <a color='lightblue' href='https://ocademy.cc'><u style='color:lightblue;'>Ocademy</u></a>."

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub.
  colab_url: "https://colab.research.google.com"
  thebe: true  # there is issues for now, https://github.com/ocademy-ai/machine-learning/issues/46


sphinx:
  config:
    html_favicon: favicon.ico
    html_extra_path: ["assets", "logo.png"]
  extra_extensions:
    - sphinxcontrib.mermaid
    - sphinxcontrib.wavedrom
    - sphinxcontrib.plantuml
    - sphinxcontrib.tikz
    - sphinxcontrib.blockdiag
    - sphinxcontrib.drawio
    - sphinxcontrib.quizdown

