name: open-machine-learning-jupyter-book
channels:
  - conda-forge
dependencies:
  - python=3.10
  - nbmake
  - pip
  - pip:
    - sphinx==4.5.0
    - pytest
    - jsonschema[format-nongpl]
    - pandas
    - numpy
    - matplotlib
    - pywaffle
    - scikit-learn
    - scipy
    - seaborn
    - tensorflow
    - jupyter-book==0.13.1
    - notebook
    - jupyter_contrib_nbextensions
    - sphinxcontrib-mermaid
    - sphinxcontrib-wavedrom
    - sphinxcontrib-plantuml
    - sphinxcontrib-tikz
    - sphinxcontrib-blockdiag
    - sphinxcontrib-drawio
    - git+https://github.com/bonartm/sphinxcontrib-quizdown.git
    
