name: open-machine-learning-jupyter-book
channels:
  - conda-forge
dependencies:
  - python=3.8
  - sphinx
  - pip
  - pip:
    - pytest
    - pandas
    - numpy
    - matplotlib
    - scikit-learn
    - seaborn
    - tensorflow
    - jupyter-book
    - sphinxcontrib-mermaid
    - sphinxcontrib-wavedrom
    - sphinxcontrib-plantuml
    - sphinxcontrib-tikz
    - sphinxcontrib-blockdiag
    - sphinxcontrib-drawio
    - git+https://github.com/bonartm/sphinxcontrib-quizdown.git