name: open-machine-learning-jupyter-book
channels:
  - conda-forge
dependencies:
  - python=3.9
  - nbmake
  - pip
  - pip:
    - pytest==7.2.0
    - pandas==1.5.2
    - numpy==1.24.1
    - jsonschema==2.6.0
    - matplotlib==3.6.2
    - pywaffle==1.1.0
    - scikit-learn==1.2.0
    - scipy==1.10.0
    - seaborn==0.12.2
    - tensorflow==2.11.0
    - jupyter-book==0.13.1
    - notebook==6.5.2
    - xgboost==1.6.2
    - imblearn
    - jupyter_contrib_nbextensions==0.7.0
    - jupyter-sphinx==0.3.2
    - pydata-sphinx-theme==0.8.1
    - sphinx_design==0.1.0
    - sphinx-book-theme==0.3.3
    - sphinx-comments==0.0.3
    - sphinx-copybutton==0.5.2
    - sphinx-external-toc==0.2.4
    - sphinx-jupyterbook-latex==0.4.7
    - sphinx-multitoc-numbering==0.1.3
    - sphinx-thebe==0.1.2
    - sphinx-togglebutton==0.3.2
    - sphinx==4.2.0
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-bibtex==2.5.0
    - sphinxcontrib-blockdiag==3.0.0
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-drawio==0.0.16
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-mermaid==0.7.1
    - sphinxcontrib-plantuml==0.24.1
    - sphinxcontrib-serializinghtml==1.1.5
    - sphinxcontrib-tikz==0.4.16
    - sphinxcontrib-wavedrom==3.0.4
    - git+https://github.com/innovationOUtside/ipython_magic_tikz.git
    - git+https://github.com/bonartm/sphinxcontrib-quizdown.git
    - tqdm
    - fastai    
