name: ocademy-machine-learning-assignments
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas==1.5.2
    - numpy==1.24.1
    - matplotlib==3.6.2
    - pywaffle==1.1.0
    - scikit-learn==1.2.0
    - scipy==1.10.0
    - seaborn==0.12.2
    - nbgitpuller
    - ipython
    - vdom
    - jupyterlab
    - jupyterlab_launcher>=0.5.0
    - pytest
    - jupyterlab-pytutor
    - lckr-jupyterlab-variableinspector
    - jupyterlab_widgets
    - tqdm
