name: pr-main-awesome

on:
  push:
    branches:
      - main
    paths:
      - 'awesome/database/data.db'

jobs:
  compare-dbs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SQLite
      run: sudo apt-get install sqlite3
      
    - name: Convert current branch database to dump
      run: sqlite3 awesome/database/data.db .dump > current_data.dump
      continue-on-error: true

    - name: Get target branch database content
      run: |
        wget -O target_data.db https://raw.githubusercontent.com/${{ github.repository }}/main/awesome/database/data.db
        sqlite3 target_data.db .dump > target_data.dump
      continue-on-error: true
      
    - name: Show database differences
      run: diff -a target_data.dump current_data.dump || true

    - name: Install dependencies
      run: |
        cd awesome
        npm install

    - name: Set environment variables 
      run: |
        export EMAIL=${{ secrets.EMAIL }}
        export PASSWORD=${{ secrets.PASSWORD }}
        export AWS_APPSYNC_AUTHENTICATIONTYPE=${{ secrets.AWS_APPSYNC_AUTHENTICATIONTYPE_TEST }}
        export AWS_APPSYNC_GRAPHQLENDPOINT=${{ secrets.AWS_APPSYNC_GRAPHQLENDPOINT_TEST }}
        export AWS_APPSYNC_REGION=${{ secrets.AWS_APPSYNC_REGION_TEST }}
        export AWS_COGNITO_IDENTITY_POOL_ID=${{ secrets.AWS_COGNITO_IDENTITY_POOL_ID_TEST }}
        export AWS_COGNITO_REGION=${{ secrets.AWS_COGNITO_REGION_TEST }}
        export AWS_COGNITO_SIGNUP_ATTRIBUTES=${{ secrets.AWS_COGNITO_SIGNUP_ATTRIBUTES_TEST }}
        export AWS_PROJECT_REGION=${{ secrets.AWS_PROJECT_REGION_TEST }}
        export AWS_USER_POOLS_ID=${{ secrets.AWS_USER_POOLS_ID_TEST }}
        export AWS_USER_POOLS_WEB_CLIENT_ID=${{ secrets.AWS_USER_POOLS_WEB_CLIENT_ID_TEST }}

    - name: Synchronize local and cloud databases
      run: |
        cd sync
        node index.js
